# Vagrant file LB2 by András Horber
# Version 1.0

Vagrant.configure(2) do |config|
  # Configuring VM: Proxy
  config.vm.define "Proxy" do |proxy|
    proxy.vm.box = "ubuntu/bionic64"
    proxy.vm.provider "virtualbox" do |vb|
      vb.memory = "341"  
    end
    proxy.vm.hostname = "M300-Proxy"
    proxy.vm.network "private_network", ip: "192.168.255.10"
    proxy.vm.network "public_network", bridge: "Intel(R) Ethernet Connection (2) I218-V", ip: "192.168.0.52"
    proxy.vm.synced_folder ".", "/vagrant" 
    proxy.vm.provision "shell", path: "Scripts/default.sh"
    proxy.vm.provision "shell", path: "Scripts/proxy.sh"
  end
  # Configuring VM: DB
  config.vm.define "DB" do |db|
    db.vm.box = "ubuntu/bionic64"
    db.vm.provider "virtualbox" do |vb|
      vb.memory = "512"  
    end
    db.vm.hostname = "M300-DB"
    db.vm.network "private_network", ip: "192.168.255.20"
    db.vm.synced_folder ".", "/vagrant" 
    db.vm.provision "shell", path: "Scripts/default.sh"
    db.vm.provision "shell", path: "Scripts/db.sh"
  end
  # Configuring VM: WEB01
  config.vm.define "Web01" do |web01|
    web01.vm.box = "ubuntu/bionic64"
    web01.vm.provider "virtualbox" do |vb|
      vb.memory = "341"  
    end
    web01.vm.hostname = "M300-WEB01"
    web01.vm.network "private_network", ip: "192.168.255.30"
    web01.vm.synced_folder ".", "/vagrant" 
    web01.vm.provision "shell", path: "Scripts/default.sh"
    web01.vm.provision "shell", path: "Scripts/web.sh"
  end
  # Configuring VM: WEB02
  config.vm.define "Web02" do |web02|
    web02.vm.box = "ubuntu/bionic64"
    web02.vm.provider "virtualbox" do |vb|
      vb.memory = "341"  
    end
    web02.vm.hostname = "M300-WEB02"
    web02.vm.network "private_network", ip: "192.168.255.31"
    web02.vm.synced_folder ".", "/vagrant" 
    web02.vm.provision "shell", path: "Scripts/default.sh"
    web02.vm.provision "shell", path: "Scripts/web.sh"
  end
end